version: '3.8'

services:
  db:
    image: postgres:13
    ports:  
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: random_password_123!
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
    environment:
      DATABASE_URL: postgresql://postgres:random_password_123!@db:5432/task_db
    networks:
      - default

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env.dev
    networks:
      - default

volumes:
  db_data:

networks:
  default: