version: '3.8'

services:
  db:
    image: postgres:13
    container_name: trially-tasks-db-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hola
      POSTGRES_DB: task_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env.dev
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: trially-tasks-backend-1
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.dev
    environment:
      DATABASE_URL: postgresql://postgres:hola@db:5432/task_db
    networks:
      - default

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: trially-tasks-frontend-1
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client # Bind mount volume. Directly links the host directory to the container directory. Useful for development to share code and dependencies.
      - /client/node_modules # Named volume. Docker manages the volume's location. Data is persisted between container restarts but not directly linked to my project's directory on the host machine.
    depends_on:
      - backend
    env_file:
      - .env.dev
    networks:
      - default
    environment:
      NODE_ENV: development

volumes:
  db_data:

networks:
  default:
    driver: bridge